### DISCUSSION TITLE
Can this be used with Homepage?

### DISCUSSION THREAD

**Discussion by pommee** [pommee/goaway#4] [Q&A]
**Q: Can this be used with Homepage?**

**A**: Yes!  
Homepage has documentation related to creating custom widgets, which you can find [here](https://gethomepage.dev/widgets/services/customapi/).  
An example widget containing some example stats fetched from the GoAway API:  
```yaml
- Network:
    - GoAway:
        description: DNS Sinkhole
        siteMonitor: 'http://<goaway-ip>:8080'
        widget:
          type: customapi
          url: 'http://<goaway-ip>:8080/api/server'
          method: GET
          mappings:
            - field: version
              label: Version
              format: text
            - field: cpuUsage
              label: CPU usage
              format: number
            - field: dbSize
              label: DB Size
              format: number
            - field: usedMem
              label: Memory usage
              format: number
```
![image](https://github.com/user-attachments/assets/63e53ae4-db65-4a39-bfb5-457c16dee100)
