### ISSUE TITLE
Docker volume configuration is problematic

### ISSUE THREAD

**Issue by sergi0g** [pommee/goaway#22]
**Describe the bug**
As far as I can tell from the example compose, Goaway is meant to be run with the `/home/appuser` directory mounted on a Docker volume. This same directory contains the scripts to start/manage the container and the `goaway` binary. Your solution of dynamically creating a named volume will work, because it's empty and does not interfere with the files.
However, if I want to use a bind mount to add files (e.g. preconfigure `settings.yaml`), the files in `/home/appuser` are entirely replaced, due to how Docker mounts work. Additionally, I'm concerned that the files are copied to the volume and read from there every time, which would result in the old binary being used even after the container is updates. Note that I have not tested this.

**To Reproduce**
1. Download the example `settings.yaml` to your computer
2. Create a Docker compose file that mounts it in `/home/appuser`
  ```yaml
  services:
  goaway:
    image: pommee/goaway:0.51.1
    restart: unless-stopped
    ports: # Ignore the web interface port here, I'm using traefik for that
      - ${DNS_PORT:-53}:53/tcp
      - ${DNS_PORT:-53}:53/udp
    volumes:
      - ${APP_DATA_DIR}/data:/home/appuser/ # This directory contains my `settings.yaml`. If I mount it individually, then the DB can't be stored
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
  ```
3. Try starting the compose. It will fail because `start.sh` wasn't found and was overwritten by the mount

**Expected behavior**
This _is_ the expected behaviour, given Docker's limitations. What's needed is a better design. Never expect the user to mount a directory in a place where existing files would be overwritten (unless of course there is a reason).
I can suggest 2 simple ways to fix this:
1. Store anything you want persisted (`settings.yaml`, DB) in a `data` folder in `/home/appuser` and have the user mount just that. (Easiest and cleanest, but requires you to do a major SemVer update)
2. Keep the existing directory for the DB and settings and move the binary and scripts to a location somewhere higher up (e.g. `/app`)

**Screenshots & Logs**
When starting the container:
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "./start.sh": stat ./start.sh: no such file or directory: unknown
```

**Please complete the following information:**
 - OS: Irrelevant
 - Architecture: Irrelevant
 - GoAway Version: Probably also irrelevant, but for anyone viewing this in the future `v0.51.1`

**Additional context**
That's enough criticism for now. Goaway looks like a really promising alternative to other solutions. I love the modern UI. Keep up the good work!
