### ISSUE TITLE
Updating the version via GUI reverts password to the one generated in log

### ISSUE THREAD

**Issue by BackedUpBooty** [pommee/goaway#24]
**Describe the bug**
Password changed in GUI gets overwritten on version update

**To Reproduce**
1. Install using docker (in this instance on a proxmox LXC)
2. Sign in using the provided password generated in the logs
3. Go to settings and change the password
4. Click 'update' when notified in the GUI of a new version
5. At some point the login token expires
6. Attempt to log in with chosen password
7. Fail
8. Search logs, find the generated password, use that
9. Succeed

There are no supporting logs in this. The only log messages which appear are if the user is not recognized, not the password being incorrect.

**Comment by BackedUpBooty** [comment]
Some more strange behaviour. Today I did a fresh install, left it for a while. Didn't make any changes at all (no additional lists, no password change). After a few hours it had logged out, and now won't allow me to log in with the original credentials.

**Comment by pommee** [comment]
This sounds very odd. I have only let it sit until logout a couple of times, but then the login process works as it should with the latest password. Neither do I see how the update process would affect the state.  

> After a few hours it had logged out, and now won't allow me to log in with the original credentials.

Does it allow you to login with the latest password in this case?

Will take a look at this when I have some spare time over. Might need to add some more debug logs to make the investigation easier.

**Comment by BackedUpBooty** [comment]
Sorry for the late reply.

> 
> > After a few hours it had logged out, and now won't allow me to log in with the original credentials.
> 
> Does it allow you to login with the latest password in this case?

Yes it does. But as per my later comment, I did a fresh install (didn't go ahead and add all my lists this time) and made no changes at all to access credentials. After X amount of time it logged me out, and then wouldn't log in at all with the same password.

I've tested it on 3 different types of system (Proxmox Ubuntu VM, Proxmox LXC, Synology NAS) and it's done the same for me every time. Using the compose or the run command makes no difference. 

Normally I'd think this was my fault / I'm doing something wrong, but agreed that some additional logging would be helpful here.

**Comment by pommee** [comment]
@BackedUpBooty Sorry for not completely understanding the picture here. Let's break it down.

1. Fresh install
2. Log in
3. No password change (i.e still supposed to use the generated one going forward)
4. Logged out after X amount of time
5. Can't login with the generated password

Is this correct?

**Comment by BackedUpBooty** [comment]
@pommee yes exactly right. sorry for the delay, I decided to create a fresh instance in a fresh LXC again just in case, and that's what I'm experiencing. I get the little modal popup bottom right which says 'Warning Invalid Credentials'.

**Comment by pommee** [comment]
I am interested to know if the generated password is stored in your `user` table after this occurs.  
It should look something similar to: `$2a$10$Y8Rny3g5z....Y8Rny3g5z...`.  

**Please do not share the full value as it is a password**

**Comment by BackedUpBooty** [comment]
> I am interested to know if the generated password is stored in your `user` table after this occurs

Where can I find the user table?

**Comment by pommee** [comment]
It is stored in the database file, located at "./data/database.db".

**Comment by BackedUpBooty** [comment]
![Image](https://github.com/user-attachments/assets/ce3992b0-0bb4-4b21-8565-91b11f8110f4)

To be honest I'm not sure I'm looking in the right place, but this is the only place I can find 'password' written that isn't to do with one of the lists I set it to use. 

EDIT: Ok I should have checked the logs first. So this time it didn't display the same behaviour for a day, and then not until I restarted the VM. It looks like the password has been changed as none of the data persisted. I don't know why this would be the case, no other containers have an issue when restarting. 

my compose is as follows, it's on a debian VM in proxmox.

```
goaway:
    image: pommee/goaway:latest
    container_name: goaway
    build: .
    volumes:
      - goaway_data:/home/appuser
    environment:
      - DNS_PORT=${DNS_PORT:-53}
      - WEBSITE_PORT=${WEBSITE_PORT:-8080}
    ports:
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/udp"
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/tcp"
      - "${WEBSITE_PORT:-8080}:${WEBSITE_PORT:-8080}/tcp"
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW

volumes:
  goaway_data:
    name: goaway_data
```
