### ISSUE TITLE
Warnings about not being able to save logs

### ISSUE THREAD

**Issue by sbcrumb** [pommee/goaway#39]
**Describe the bug**
Docker Log contains messages about not being able to log

**To Reproduce**
docker logs -f goway(or container name)

**Expected behavior**
Be able to log

**Screenshots & Logs**
```
2025/06/23 15:12:08 [WARN] Error while saving logs, reason: could not save request log: constraint failed: NOT NULL constraint failed: request_log.ip (1299)
```

**Please complete the following information:**
 - OS: [Debian 12]
 - Architecture [e.g. amd64]
 - GoAway Version [e.g. 0.54.6]

**Additional context**

**docker-compose.yml**

```yml
services:
  goaway:
    image: pommee/goaway:latest
    container_name: goaway
    restart: unless-stopped
    volumes:
      - /opt/goaway:/app/config
      - /opt/goaway:/app/data  
    environment:
      - DNS_PORT=${DNS_PORT:-53}
      - WEBSITE_PORT=${WEBSITE_PORT:-80}
    ports:
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/udp"
      - "${DNS_PORT:-53}:${DNS_PORT:-53}/tcp"
      - "${WEBSITE_PORT:-80}:${WEBSITE_PORT:-80}/tcp"
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
```

**settings.yml**

```yml
dns:
    address: ""
    port: 53
    cacheTTL: 360
    preferredUpstream: 192.168.253.1:53
    upstreamDNS:
        - 192.168.253.1:53
    udpSize: 0
api:
    port: 80
    authentication: true
    rateLimit:
        enabled: false
        maxTries: 0
        window: 0
statisticsRetention: 7
loggingEnabled: true
logLevel: 1
inAppUpdate: false
```
